# get an AUTHORIZATION_TOKEN
# see https://rasa.com/docs/rasa-x/pages/http-api#tag/Authentication
POST  http://XXX.XXX.XXX.XXX/api/auth
content-type: application/json

{
    "username": "admin",
    "password": "safe_credential"

}
###

# dump a conversation given a CONVERSATION_ID
# see: https://rasa.com/docs/rasa-x/pages/http-api#operation/getConversationInFormat
GET http://XXX.XXX.XXX.XXX/api/conversations/CONVERSATION_ID 
content-type: application/json
Authorization: Bearer AUTHORIZATION_TOKEN




