language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 10
policies:
- name: MemoizationPolicy
- name: KerasPolicy
  epochs: 100
- name: MappingPolicy
