language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
- name: custom.customNLU.MyComponent
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
