version: '3.4'

services:
  analytics:
    image: analytics
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/app
    working_dir: /app
    entrypoint: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - 8000:8000
  
  rasa-server:
    image: rasa-server
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    entrypoint: make run-bot
    ports:
      - 5005:5005

  db:
    image: docker.io/bitnami/postgresql:11
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRESQL_PASSWORD=safe_credential'
      - 'POSTGRESQL_DATABASE=rasa'
