version: '3.0'
services:
  rasa:
    image: rasa/rasa:1.6.1
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run 
      - --enable-api
  action_server:
    image: rasa/rasa-sdk:1.6.1
    volumes:
      - ./actions:/app/actions