
name: nlu-hyperopt
on: [pull_request]

jobs:
  nlu-hyperopt:
    name: NLU hyperoptimization
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade "pip<20"
          pip install -r requirements-dev.txt
      - uses: actions/checkout@v2
      - name: Shuffle and split data
        run: |
          rasa data split nlu
          mv train_test_split/test_data.md hyperopt_data/validation.md
          mv train_test_split/training_data.md hyperopt_data/train.md
      - name: NLU hyperoptimization
        id: nluhyperopt
        uses: RasaHQ/nlu-hyperopt@rasa-1-compat
        env:
          DATA_DIR: $GITHUB_WORKSPACE/hyperopt_data
          SEARCH_SPACE: $GITHUB_WORKSPACE/hyperopt_data/space.py
          MAX_EVALS: 1
          TARGET_METRIC: f1_score
    # - id: files
    #   uses: jitterbit/get-changed-files@v1
    # - run: |
    #     for changed_file in ${{ steps.files.outputs.all }}; do
    #       echo "Do something with this ${changed_file}."
    #     done
    # - name: Cross-validate NLU model
    #   id: cvnlu
    #   run: |
    #     echo "Would cross validate"
    #   if: contains( steps.files.outputs.all, 'data/nlu' )
    # - name: post cross-val results to PR
    #   if: steps.cvnlu.outcome == 'success'
    #   run: |
    #     echo "Would post CV result"
    # - name: Train Model
    #   id: train
    #   if: |
    #       contains(  ${{ steps.files.outputs.all }}, data/ ) 
    #       || contains(  ${{ steps.files.outputs.all }}, config.yml ) 
    #       || contains(  ${{ steps.files.outputs.all }}, domain.yml )
    #   run: |
    #     echo "Would have trained a model"
    # - name: Test Training Stories
    #   run: |
    #     echo "Would have tested stories"
    #   if: |
    #       contains(  ${{ steps.files.outputs.all }}, data/core/ ) 
    #       || contains(  ${{ steps.files.outputs.all }}, config.yml ) 
    #       || contains(  ${{ steps.files.outputs.all }}, domain.yml )
    # - name: Upload model
    #   if: |
    #       github.ref == 'refs/heads/master' 
    #       && steps.train.outcome == 'success'
    #   run: |
    #       echo "Would have uploaded a model"