
name: Build and Deploy
on: [pull_request]

jobs:
  training-testing:
    name: Testing Stories
    runs-on: ubuntu-latest
    steps:
    - id: files
      uses: jitterbit/get-changed-files@v1
    - run: |
        for changed_file in ${{ steps.files.outputs.all }}; do
          echo "Do something with this ${changed_file}."
        done
    - name: Cross-validate NLU model
      id: cvnlu
      run: |
        echo "Would cross validate"
      if: contains( steps.files.outputs.all, 'data/nlu' )
    - name: post cross-val results to PR
      if: steps.cvnlu.outcome == 'success'
      run: |
        echo "Would post CV result"
    - name: Train Model
      id: train
      if: |
          contains(  ${{ steps.files.outputs.all }}, data/ ) 
          || contains(  ${{ steps.files.outputs.all }}, config.yml ) 
          || contains(  ${{ steps.files.outputs.all }}, domain.yml )
      run: |
        echo "Would have trained a model"
    - name: Test Training Stories
      run: |
        echo "Would have tested stories"
      if: |
          contains(  ${{ steps.files.outputs.all }}, data/core/ ) 
          || contains(  ${{ steps.files.outputs.all }}, config.yml ) 
          || contains(  ${{ steps.files.outputs.all }}, domain.yml )
    - name: Upload model
      if: |
          github.ref == 'refs/heads/master' 
          && steps.train.outcome == 'success'
      run: |
          echo "Would have uploaded a model"