name: Continuous Integration
on:
  push:
    branches:
    - master

jobs:
  docker:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest

    steps:
        - name: Set Build ID from PR Ref
          run: |
            echo $GITHUB_RUN_ID
            echo $GITHUB_RUN_NUMBER